version: "3.6"

services:

  arm-build-server-scaffold-svc:
    image: sixeyed/iotkit-arm-build-server
    build:
      context: ./services/arm-build-server

  github-repo-scaffold-svc:
    image: sixeyed/iotkit-github-repo
    build:
      context: ./services/github-repo