version: "3.6"

services:

  arm-build-server-scaffold-svc:
    image: sixeyed/iotkit-arm-build-server
    build:
      context: ./services/arm-build-server

  github-repo-scaffold-svc:
    image: sixeyed/iotkit-github-repo
    build:
      context: ./services/github-repo

  arm-device-scaffold-svc:
    image: sixeyed/iotkit-arm-device
    build:
      context: ./services/arm-device

  docker-hub-repo-scaffold-svc:
    image: sixeyed/iotkit-docker-hub-repo
    build:
      context: ./services/docker-hub-repo