apiVersion: v1alpha1
generated: "2018-06-13T09:24:07.392654524Z"
kind: RepositoryContent
services:
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: arm-build-server
    platforms:
      - linux
  spec:
    description: Arm build server on AWS
    icon: https://raw.githubusercontent.com/sixeyed/app-template-iot/master/img/jenkins.png
    source:
      image: sixeyed/iotkit-arm-build-server
    title: Jenkins running on an A1 AWS instance for building Arm projects
    parameters:
    - name: projectName
      description: Project name
      type: string
    - name: accessKeyId
      description: AWS access key Id
      type: string
    - name: secretAccessKey
      description: AWS secret access key
      type: string
    - name: defaultRegion
      defaultValue: us-east-2
      description: Default region
      type: string
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: github-repo
    platforms:
      - linux
  spec:
    description: Create new GitHub repo
    icon: https://raw.githubusercontent.com/sixeyed/app-template-iot/master/img/github.png
    source:
      image: sixeyed/iotkit-github-repo
    title: GitHub repo
    parameters:
    - name: username
      description: Username
      type: string
    - name: accessToken
      description: Access token
      type: string
    - name: repoName
      description: Repository name
      type: string
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: docker-hub-repo
    platforms:
      - linux
  spec:
    description: Connect to Docker Hub
    icon: https://raw.githubusercontent.com/sixeyed/app-template-iot/master/img/docker.png
    source:
      image: sixeyed/iotkit-docker-hub-repo
    title: Connect to Docker Hub
    parameters:
    - name: username
      description: Username
      type: string
    - name: password
      description: Password
      type: string      
    - name: repoName
      description: Repository name
      type: string      
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: arm-device
    platforms:
      - linux
  spec:
    description: Deploy to local Arm device
    icon: https://raw.githubusercontent.com/sixeyed/app-template-iot/master/img/arm.png
    source:
      image: sixeyed/iotkit-arm-device
    title: Deploy to local Arm device
    parameters:
    - name: ipAddress
      description: IP address
      type: string
    - name: username
      description: SSH username
      type: string
    - name: password
      description: SSH password
      type: string      
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: device-demo
    platforms:
      - linux
  spec:
    description: Sample IoT device app
    icon: https://raw.githubusercontent.com/sixeyed/app-template-iot/master/img/dotnet.png
    source:
      image: sixeyed/iotkit-device-demo
    title: Sample IoT device app
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: service-demo
    platforms:
      - linux
  spec:
    description: Sample IoT service
    icon: https://raw.githubusercontent.com/sixeyed/app-template-iot/master/img/dotnet.png
    source:
      image: sixeyed/iotkit-service-demo
    title: Sample IoT service
    parameters:
    - name: externalPort
      defaultValue: "8081"
      description: External port      
      type: hostPort
templates:
- apiVersion: v1alpha1
  kind: ApplicationTemplate
  metadata:
    name: iot-starter-kit
    platforms:
    - linux
  spec:
    description: IoT Starter kit with Jenkins on A1
    services:
    - name: Build server
      serviceId: arm-build-server
    - name: GitHub repo
      serviceId: github-repo
    - name: Docker Hub repo
      serviceId: docker-hub-repo    
    - name: Local device
      serviceId: arm-device    
    - name: Sample Iot device app
      serviceId: service-demo   
    - name: Sample IoT service
      serviceId: service-demo
    title: IoT Starter kit with Jenkins on A1