version: '3.7'

services:

  # Will this comment get merged?
  {{ .Name }}:
    build: {{ .Name }}
    ports:
      - {{ .Parameters.externalPort }}:80
    secrets:
      - github-username
      - github-repo
      - jenkins-url
      - jenkins-username
      - jenkins-password
      - docker-hub-username
  