version: '3.7'

services:

  jenkins:
    image: iotkitdemo/jenkins:2.176.1
    ports:
      - "8080:8080"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend
    configs:
      - github-username
      - github-repo
    secrets:
      - jenkins-username
      - jenkins-password
      - docker-hub-username
      - docker-hub-password
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.70'
          memory: 1000M

networks:
  frontend:

volumes:
  jenkins-home:

configs:
  github-username:
    external: true
  github-repo:
    external: true

secrets:
  jenkins-username:
    external: true
  jenkins-password:
    external: true
  docker-hub-username:
    external: true
  docker-hub-password:
    external: true
  