version: '3.7'

services:

  jenkins:
    image: iotkitdemo/jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins-home:/var/jenkins_home
    networks:
      - frontend
    secrets:
      - jenkins-username
      - jenkins-password
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.70'
          memory: 1000M

networks:
  frontend:

volumes:
  jenkins-home:

secrets:
  jenkins-username:
    external: true
  jenkins-password:
    external: true
  